[program:assinador-python]
directory=/var/www/vhosts/gea/assinador-python
command=/var/www/vhosts/gea/assinador-python/venv/bin/gunicorn -w 4 -b 127.0.0.1:5000 run:app
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/www/vhosts/gea/assinador-python/logs/error.log
stdout_logfile=/var/www/vhosts/gea/assinador-python/logs/app.log
environment=PATH="/var/www/vhosts/gea/assinador-python/venv/bin"

[group:assinador]
programs=assinador-python